### ISSUE TITLE
Shouldn't refactor the signature of main()

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#111]
main() is a special case; it's signature can't change. See the test that is part of https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/08c7e3a42a1d3c48b520788e883e7344608b5934. Filed with @walleXD.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/862627132877233)

**Comment by khatchad** [comment]
This may be a good first bug to delve into the core functionality.

**Comment by khatchad** [comment]
@saledouble please have a look at this issue.

**Comment by khatchad** [comment]
It should allow you to get familiar with the code.

**Comment by ponder-sync** [comment]
➤ Yiming Tang commented:

OK. I will. Thanks.

**Comment by khatchad** [comment]
@saledouble We'll also need to make sure that the associated test case passes.

**Comment by orenwf** [comment]
Two tests are needed. 
- `RefactoringSettings` contains `BRIDGE_EXTERNAL`, so the resulting `RefactoringStatus` should be `INFO` because the argument entity to `main()` that is null-type dependent can be bridged out.
- `RefactoringSettings` does not contain `BRIDGE_EXTERNAL` so the resulting `RefactoringStatus` should be `ERROR`
