### ISSUE TITLE
Bridge elements

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#65]
Per #54, we are collecting elements that are "bridgable." If the developer wants bridging, then we should transform such elements to optionals but utilizing bridge (unwrapper) methods.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/758533986942894)

**Comment by orenwf** [comment]
[This issue seems more like a specification, which has been implemented. I believe it is correct, but if we find bugs we can open further issues (and reference this)](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/89f2d26c62ac9a83d9f723598d3ad8372e49aec9/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactoringSettings.java#L26-L33)
