### ISSUE TITLE
Factor out common superclass for the seeder and propagator

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#88]
This is actually a functional change because we need behavior to be consistent between the propagator and seeder. However, there may be some differences.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/810259548693208)

**Comment by orenwf** [comment]
ASTNodes that wouldn't be treated the same in Seeder / Propagator:

`void process()` in seeding the root node would have a visitor pattern called on it to mine for `NullLiteral` values, and then the appropriate `process(node)` method gets called on those in the `visit(NullLiteral node)` method. In propagation, we have the `ASTNode` instance already, which would be an identifier of some kind, an instance of `Name` in almost all cases, and so we just need to `process(node.getParent())`.

`void process(ArrayAccess node)` in Propagation needs to check if the immediate sub-expression of the `ArrayAccess.getIndex()` method return, while in Seeder we don't care because it would be a syntax error.

`void process(ArrayCreation node)` in propagation and seeding, difference same as `ArrayAccess`.

`void process(Assignment node)` and `void process(InfixExpression node)` in propagation we `process(node.getLeftHandSide())` and `process(node.getRightHandSide())` but in seeding we just `process` the side that isn't null. Not 100% clear on the reason why both sides are required in propagation but this is how it's currently designed.

... more to follow ....

**Comment by orenwf** [comment]
See #107 for explanation and PR that addresses this.
